### ISSUE TITLE
[NVM] Update recommended

### ISSUE THREAD

**Issue by Kochise** [wenuam/wm_doc_latex#1]
Regarding https://github.com/mermaid-js/mermaid-cli/issues/72

Obviously there is a problem upgrading **nvm** :

https://github.com/coreybutler/nvm-windows/issues/671 (UAC mitigation)
https://github.com/coreybutler/nvm-windows/issues/767 (exit status 1: Access is denied)
https://github.com/coreybutler/nvm-windows/issues/820
https://github.com/coreybutler/nvm-windows/issues/857 (elevate.vbs)

**Comment by wenuam** [comment]
Done.
